### ISSUE TITLE
Can you also share your bios settings ?

### ISSUE THREAD

**Issue by kemalsanli** [kreactnative/hackintosh-tuf-fx505gd-bigSur#1]
Hello i have also FX505GD, and , i am also trying to install macos big sur but my computer gets stuck when i select second installation option(Macos installer) and gives error when apple logo appeared :
"AppleActuatorDeviceUserClient::stop entered"

like in this video: https://www.youtube.com/watch?v=HFmvxBo2dHw but first error message is "AppleActuatorDeviceUserClient::stop entered"

My hardware is: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz Intel(R) Wireless-AC 9462 Intel(R) UHD Graphics 630 GeForce GTX 1050 (4 GB)  ASUS FX505GD, also i have stock wifi card ac 9462.

Can you please share your bios options and maybe ideas ,

thanks in advance ^^

**Comment by haziqsupangat** [comment]
Hi

I just follow the opencore vanilla bios setup, like disabling secure boot, fast boot, enabling ahci mode for sata. i think that’s the only things that i change in the bios other than adding the boot option since i dual boot with windows.

Hope this helps

**Comment by kemalsanli** [comment]
Thank you for your answer, i will try again. hope you have a nice day.
